/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 cagaste.gltf --transform 
Files: cagaste.gltf [30.41MB] > cagaste-transformed.glb [1.68MB] (94%)
Author: 7PLUS (https://sketchfab.com/7plus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anthro-shark-a0f668cc3b3440c1bc29e2a7ecda9b54
Title: Anthro Shark
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shark(props) {
  const { nodes, materials } = useGLTF('/cagaste-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.CHEST} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.HEAD} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.material} />
      <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.material_3} />
      <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.TEETHEYETAIL} />
    </group>
  )
}

useGLTF.preload('/cagaste-transformed.glb')
