/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 godzilla.gltf --transform 
Files: godzilla.gltf [42.35MB] > godzilla-transformed.glb [2.33MB] (94%)
Author: savounited (https://sketchfab.com/savounited)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/godzilla-heisei-godzilla-648078eb0fd8405fb46d646bf32c6208
Title: Godzilla - Heisei Godzilla
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Godzilla(props) {
  const { nodes, materials } = useGLTF('/godzilla-transformed.glb')
  
  // Escala uniforme en todas las direcciones (x2)
  const scale = 1.4;

  return (
    <group {...props} dispose={null} scale={scale}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.pl01_coverglass} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.pl01_color} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.pl01_eye} />
    </group>
  )
}

useGLTF.preload('/godzilla-transformed.glb')
